CREATE DATABASE login;

CREATE TABLE users(
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(255) NULL,
	first_name VARCHAR(255) NULL,
	last_name VARCHAR(255) NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);